steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/firetools', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/firetools']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'firetools',
        '--image', 'gcr.io/$PROJECT_ID/firetools',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]
images:
  - gcr.io/$PROJECT_ID/firetools
